mods.astralsorcery.Lightwell.addLiquefaction(<cavern:cave_item>, <liquid:astralsorcery.liquidstarlight>, 0.4, 12, 0);

recipes.addShaped(<iceandfire:dragonegg_red>, [[<iceandfire:dragonscales_red>, <iceandfire:ice_dragon_flesh>, <iceandfire:dragonscales_red>],[<iceandfire:fire_dragon_blood>, <iceandfire:fire_dragon_heart>, <iceandfire:fire_dragon_blood>], [<iceandfire:dragonscales_red>, <minecraft:dragon_egg>, <iceandfire:dragonscales_red>]]);
recipes.addShaped(<iceandfire:dragonegg_green>, [[<iceandfire:dragonscales_green>, <iceandfire:ice_dragon_flesh>, <iceandfire:dragonscales_green>],[<iceandfire:fire_dragon_blood>, <iceandfire:fire_dragon_heart>, <iceandfire:fire_dragon_blood>], [<iceandfire:dragonscales_green>, <minecraft:dragon_egg>, <iceandfire:dragonscales_green>]]);
recipes.addShaped(<iceandfire:dragonegg_bronze>, [[<iceandfire:dragonscales_bronze>, <iceandfire:ice_dragon_flesh>, <iceandfire:dragonscales_bronze>],[<iceandfire:fire_dragon_blood>, <iceandfire:fire_dragon_heart>, <iceandfire:fire_dragon_blood>], [<iceandfire:dragonscales_bronze>, <minecraft:dragon_egg>, <iceandfire:dragonscales_bronze>]]);
recipes.addShaped(<iceandfire:dragonegg_gray>, [[<iceandfire:dragonscales_gray>, <iceandfire:ice_dragon_flesh>, <iceandfire:dragonscales_gray>],[<iceandfire:fire_dragon_blood>, <iceandfire:fire_dragon_heart>, <iceandfire:fire_dragon_blood>], [<iceandfire:dragonscales_gray>, <minecraft:dragon_egg>, <iceandfire:dragonscales_gray>]]);
recipes.addShaped(<iceandfire:dragonegg_silver>, [[<iceandfire:dragonscales_silver>, <iceandfire:ice_dragon_flesh>, <iceandfire:dragonscales_silver>],[<iceandfire:ice_dragon_blood>, <iceandfire:ice_dragon_heart>, <iceandfire:ice_dragon_blood>], [<iceandfire:dragonscales_silver>, <minecraft:dragon_egg>, <iceandfire:dragonscales_silver>]]);
recipes.addShaped(<iceandfire:dragonegg_sapphire>, [[<iceandfire:dragonscales_sapphire>, <iceandfire:ice_dragon_flesh>, <iceandfire:dragonscales_sapphire>],[<iceandfire:ice_dragon_blood>, <iceandfire:ice_dragon_heart>, <iceandfire:ice_dragon_blood>], [<iceandfire:dragonscales_sapphire>, <minecraft:dragon_egg>, <iceandfire:dragonscales_sapphire>]]);
recipes.addShaped(<iceandfire:dragonegg_white>, [[<iceandfire:dragonscales_white>, <iceandfire:ice_dragon_flesh>, <iceandfire:dragonscales_white>],[<iceandfire:ice_dragon_blood>, <iceandfire:ice_dragon_heart>, <iceandfire:ice_dragon_blood>], [<iceandfire:dragonscales_white>, <minecraft:dragon_egg>, <iceandfire:dragonscales_white>]]);
recipes.addShaped(<iceandfire:dragonegg_blue>, [[<iceandfire:dragonscales_blue>, <iceandfire:ice_dragon_flesh>, <iceandfire:dragonscales_blue>],[<iceandfire:ice_dragon_blood>, <iceandfire:ice_dragon_heart>, <iceandfire:ice_dragon_blood>], [<iceandfire:dragonscales_blue>, <minecraft:dragon_egg>, <iceandfire:dragonscales_blue>]]);